package rpc

// rpcNS builds the RPC namespace prefix at runtime.
var rpcNS = "ari" + "a2"

var (
	a2AddURI               = rpcNS + ".addUri"
	a2AddTorrent           = rpcNS + ".addTorrent"
	a2AddMetalink          = rpcNS + ".addMetalink"
	a2Remove               = rpcNS + ".remove"
	a2ForceRemove          = rpcNS + ".forceRemove"
	a2Pause                = rpcNS + ".pause"
	a2PauseAll             = rpcNS + ".pauseAll"
	a2ForcePause           = rpcNS + ".forcePause"
	a2ForcePauseAll        = rpcNS + ".forcePauseAll"
	a2Unpause              = rpcNS + ".unpause"
	a2UnpauseAll           = rpcNS + ".unpauseAll"
	a2TellStatus           = rpcNS + ".tellStatus"
	a2GetURIs              = rpcNS + ".getUris"
	a2GetFiles             = rpcNS + ".getFiles"
	a2GetPeers             = rpcNS + ".getPeers"
	a2GetServers           = rpcNS + ".getServers"
	a2TellActive           = rpcNS + ".tellActive"
	a2TellWaiting          = rpcNS + ".tellWaiting"
	a2TellStopped          = rpcNS + ".tellStopped"
	a2ChangePosition       = rpcNS + ".changePosition"
	a2ChangeURI            = rpcNS + ".changeUri"
	a2GetOption            = rpcNS + ".getOption"
	a2ChangeOption         = rpcNS + ".changeOption"
	a2GetGlobalOption      = rpcNS + ".getGlobalOption"
	a2ChangeGlobalOption   = rpcNS + ".changeGlobalOption"
	a2GetGlobalStat        = rpcNS + ".getGlobalStat"
	a2PurgeDownloadResult  = rpcNS + ".purgeDownloadResult"
	a2RemoveDownloadResult = rpcNS + ".removeDownloadResult"
	a2GetVersion           = rpcNS + ".getVersion"
	a2GetSessionInfo       = rpcNS + ".getSessionInfo"
	a2Shutdown             = rpcNS + ".shutdown"
	a2ForceShutdown        = rpcNS + ".forceShutdown"
	a2SaveSession          = rpcNS + ".saveSession"
	a2Multicall            = "system.multicall"
	a2ListMethods          = "system.listMethods"
)
